[book]
authors = ["dCordon"]
language = "es"
multilingual = false
src = "src"
title = "Guía de instalación de Arch Linux"
description = "Guía en formato libro con las indicaciones para instalar Arch Linux como único sistema operativo."

[build]
create-missing = false

[output.html]
git-repository-url = "https://github.com/dcordonu/arch-installation-guide"

